'use strict';
const app=document.querySelector('#app');
const STORAGE_KEY='tamagawa-quest-v2';
const DEFAULT_RECORD={plays:0,best:0,learned:[],seen:[],ruby:true,sound:false};
let record=loadRecord(),state={screen:'home',session:[],index:0,answers:[],mode:'normal',locked:false},audioContext;
const READINGS={'多摩川小学校':'たまがわしょうがっこう','多摩川':'たまがわ','大田区':'おおたく','東京都':'とうきょうと','世田谷区':'せたがやく','杉並区':'すぎなみく','矢口':'やぐち','蒲田':'かまた','田園調布':'でんえんちょうふ','武蔵新田駅':'むさしにったえき','東急多摩川線':'とうきゅうたまがわせん','山手線':'やまのてせん','東海道新幹線':'とうかいどうしんかんせん','上野駅':'うえのえき','東京駅':'とうきょうえき','荒川':'あらかわ','隅田川':'すみだがわ','河犬':'かけん','自然探索':'しぜんたんさく','教育目標':'きょういくもくひょう','上級生':'じょうきゅうせい','普通教室':'ふつうきょうしつ','管理室':'かんりしつ','多目的室':'たもくてきしつ','体育館':'たいいくかん','図書室':'としょしつ','校庭':'こうてい','芝生化':'しばふか','芝生':'しばふ','校章':'こうしょう','校歌':'こうか','開校':'かいこう','周年':'しゅうねん','記念日':'きねんび','記念':'きねん','制定':'せいてい','昭和':'しょうわ','平成':'へいせい','令和':'れいわ','西暦':'せいれき','年度':'ねんど','沿革':'えんかく','植樹式':'しょくじゅしき','新設':'しんせつ','学校':'がっこう','地域':'ちいき','川辺':'かわべ','教科':'きょうか','学習':'がくしゅう','生活':'せいかつ','問題':'もんだい','正解':'せいかい','正答':'せいとう','復習':'ふくしゅう','冒険':'ぼうけん','発見':'はっけん','出発':'しゅっぱつ','探検':'たんけん','図鑑':'ずかん','記録':'きろく','挑戦':'ちょうせん','全部':'ぜんぶ','達成':'たっせい','名人':'めいじん','博士':'はかせ','笑顔':'えがお','未来':'みらい','自然':'しぜん','住所':'じゅうしょ','帽子':'ぼうし','黄色':'きいろ','青色':'あおいろ','赤色':'あかいろ','中央':'ちゅうおう','児童':'じどう','完成':'かんせい','募集':'ぼしゅう','相手':'あいて','健康':'けんこう','立場':'たちば','表現':'ひょうげん','目標':'もくひょう','実践':'じっせん','気持':'きも','友':'とも','自分':'じぶん','考':'かんが','最後':'さいご','大切':'たいせつ','解決':'かいけつ','工夫':'くふう','方法':'ほうほう','相談':'そうだん','意見':'いけん','理由':'りゆう','無視':'むし','無理':'むり','毎日':'まいにち','失敗':'しっぱい','役割':'やくわり','活動':'かつどう','言葉':'ことば','選':'えら','聞':'き','読':'よ','強':'つよ','正':'ただ','知':'し','今':'いま','川':'かわ','花':'はな','鏡':'かがみ','矢':'や','桜':'さくら','木':'き','体':'からだ','力':'ちから','駅':'えき','年生':'ねんせい','何':'なに'};
delete READINGS['何'];
Object.assign(READINGS,{'今日':'きょう','何区':'なんく','何丁目':'なんちょうめ','何年':'なんねん','何色':'なにいろ','何月':'なんがつ','何回':'なんかい','三丁目':'さんちょうめ','一丁目':'いっちょうめ','五丁目':'ごちょうめ','南極':'なんきょく','世界':'せかい','元気':'げんき','教室':'きょうしつ','教科書':'きょうかしょ','学校生活':'がっこうせいかつ','大丈夫':'だいじょうぶ','成長':'せいちょう','解説':'かいせつ','時間制限':'じかんせいげん','全校':'ぜんこう','全':'ぜん','回答':'かいとう','回数':'かいすう','練習':'れんしゅう','予習':'よしゅう','最高':'さいこう','確認':'かくにん','参考':'さんこう','番':'ばん','出典':'しゅってん','部屋':'へや','施設':'しせつ','路線':'ろせん','電車':'でんしゃ','学年':'がくねん','誕生':'たんじょう','王':'おう','外国':'がいこく','宇宙旅行':'うちゅうりょこう','宇宙飛行士':'うちゅうひこうし','宇宙観測室':'うちゅうかんそくしつ','宇宙':'うちゅう','冒険者':'ぼうけんしゃ','海底':'かいてい','水族館':'すいぞくかん','映画館':'えいがかん','競争':'きょうそう','徒歩':'とほ','授業':'じゅぎょう','全面':'ぜんめん','場所':'ばしょ','名前':'なまえ','先':'さき','先生':'せんせい','友だち':'ともだち','宝':'たから','通':'とお','声':'こえ','必要':'ひつよう','持':'も','主':'ぬし','続':'つづ','認':'みと','休':'やす','助':'たす','伝':'つた','入学':'にゅうがく','気':'き','話':'はな','人':'ひと','次':'つぎ','青':'あお','組':'く','植':'う','新':'あたら','入':'い','出':'で','同':'おな','小':'ちい','聞':'き','流':'なが','来':'く','見':'み','言':'い','思':'おも','一度':'いちど'});
Object.assign(READINGS,{'話':'はなし','話し':'はなし','出来事':'できごと','何年生':'なんねんせい','入って':'はいって','入り口':'いりぐち','近':'ちか','学':'まな','砂':'すな','海':'うみ','題材':'だいざい','号':'ごう','紹介':'しょうかい','案内':'あんない','取り組':'とりく','順位':'じゅんい','速':'はや','答':'こた','喜':'よろこ','生まれ':'うまれ','仲間':'なかま','中心':'ちゅうしん','月の世界':'つきのせかい','大好':'だいす','色':'いろ','子ども':'こども','二人':'ふたり','一人':'ひとり','年':'ねん','公式':'こうしき','日':'にち','迎':'むか','長':'なが','歴史':'れきし','元年':'がんねん','行った':'おこなった','三つ':'みっつ','高':'たか','遠':'とお','大き':'おおき','丸':'まる','広':'ひろ','表す':'あらわす','写':'うつ','育':'そだ','心':'こころ','決':'き','想像':'そうぞう','一つ':'ひとつ','出会':'であ','何も':'なにも','目指':'めざ','困':'こま','落とし物':'おとしもの','変':'か','話し合い':'はなしあい','遊':'あそ','勝手':'かって','帰':'かえ','進':'すす','下手':'へた','夜':'よる','一歩':'いっぽ','直':'なお','少':'すこ','4月':'しがつ','5月':'ごがつ','9月':'くがつ','11月':'じゅういちがつ','10月':'じゅうがつ','1月':'いちがつ','12月':'じゅうにがつ'});
const readingKeys=Object.keys(READINGS).sort((a,b)=>b.length-a.length);
const readingRegex=new RegExp(readingKeys.join('|'),'g');
function escapeHTML(text){return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function r(text){return `<span class="ruby-text">${escapeHTML(text).replace(readingRegex,word=>`<ruby>${word}<rt aria-hidden="true">${READINGS[word]}</rt></ruby>`)}</span>`;}
function loadRecord(){try{const raw=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!raw||typeof raw!=='object')return {...DEFAULT_RECORD,learned:[],seen:[]};return {plays:Number.isInteger(raw.plays)&&raw.plays>=0?raw.plays:0,best:Number.isInteger(raw.best)&&raw.best>=0&&raw.best<=10?raw.best:0,learned:Array.isArray(raw.learned)?[...new Set(raw.learned.filter(id=>Number.isInteger(id)&&id>=1&&id<=50))]:[],seen:Array.isArray(raw.seen)?[...new Set(raw.seen.filter(id=>Number.isInteger(id)&&id>=1&&id<=50))]:[],ruby:raw.ruby!==false,sound:raw.sound===true};}catch{return {...DEFAULT_RECORD,learned:[],seen:[]};}}
function saveRecord(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(record));}catch{/* 保存できない環境でもゲームは遊べる */}}
function shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
function syncSettings(){document.body.classList.toggle('hide-ruby',!record.ruby);const ruby=document.querySelector('#ruby-toggle');ruby.innerHTML=`あ <span>ふりがな ${record.ruby?'ON':'OFF'}</span>`;ruby.setAttribute('aria-pressed',String(record.ruby));const sound=document.querySelector('#sound-toggle');sound.innerHTML=`♫ <span>音 ${record.sound?'ON':'OFF'}</span>`;sound.setAttribute('aria-pressed',String(record.sound));sound.setAttribute('aria-label',`効果音 ${record.sound?'ON':'OFF'}`);sound.title=`効果音 ${record.sound?'ON':'OFF'}`;}
function stopSpeech(){if('speechSynthesis' in window)window.speechSynthesis.cancel();}
function playSound(kind){if(!record.sound)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const notes=kind==='correct'?[523.25,659.25,783.99]:kind==='finish'?[523.25,659.25,783.99,1046.5]:[392,329.63];notes.forEach((freq,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime+i*.12;osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.07,t+.015);gain.gain.exponentialRampToValueAtTime(.001,t+.22);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+.24);});}catch{/* 音が使えなくても画面で結果を伝える */}}
function focusHeading(){requestAnimationFrame(()=>{const heading=app.querySelector('h1,h2');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}});}
function scrollTop(){window.scrollTo({top:0,behavior:'instant'});}
function schoolScene(){return `<svg viewBox="0 0 560 460" role="img" aria-label="芝生の校庭と学校、多摩川をイメージしたイラスト"><defs><pattern id="windows" width="45" height="50" patternUnits="userSpaceOnUse"><rect x="9" y="8" width="25" height="30" rx="2" fill="#96b9ab"/><path d="M21 8v30M9 22h25" stroke="#f9f5d8" stroke-width="3"/></pattern></defs><circle cx="370" cy="110" r="133" fill="#d5e5ca"/><circle cx="439" cy="81" r="32" fill="#ffdc76"/><path d="M100 141c10-17 25-14 28-4 9-27 39-23 44-6 22-8 30 6 29 14H100" fill="#fffdf3"/><path d="M359 157c8-14 19-13 23-4 10-21 32-18 37-3 20-5 24 6 25 11h-85" fill="#fffdf3"/><path d="M26 297Q260 204 540 269L574 425H5Z" fill="#a9c689"/><path d="M-6 367Q189 300 329 347T570 361v111H0Z" fill="#76b9bd"/><path d="M-6 358Q189 291 329 338T570 352" fill="none" stroke="#f3edc4" stroke-width="15"/><path d="M47 410q28-9 56 0m55-21q35-8 58 0m75 43q40-9 72 0m60-37q30-8 63 0" stroke="#c5e4dc" stroke-width="4" fill="none" stroke-linecap="round"/><path d="M155 194l164-53 157 58v18H155Z" fill="#ce8458"/><rect x="166" y="211" width="299" height="102" rx="4" fill="#fbf0ce"/><rect x="174" y="219" width="280" height="89" fill="url(#windows)"/><rect x="290" y="189" width="58" height="123" fill="#fffbdf"/><path d="M281 190l38-37 38 37" fill="#b86640"/><circle cx="319" cy="201" r="15" fill="#fffdf2" stroke="#397660" stroke-width="3"/><path d="M319 190v11l7 4" fill="none" stroke="#397660" stroke-width="2"/><rect x="301" y="269" width="37" height="44" rx="3" fill="#3d7965"/><path d="M165 315h303" stroke="#688b56" stroke-width="6" stroke-linecap="round"/><rect x="290" y="238" width="60" height="18" rx="3" fill="#e5e9d7"/><text x="320" y="251" text-anchor="middle" font-size="10" fill="#305b4c" font-family="sans-serif">多摩川小学校</text><path d="M114 280v50M500 273v40" stroke="#8c7153" stroke-width="9"/><ellipse cx="111" cy="253" rx="33" ry="43" fill="#548958"/><circle cx="95" cy="260" r="23" fill="#609b5e"/><circle cx="130" cy="266" r="23" fill="#609b5e"/><ellipse cx="497" cy="249" rx="28" ry="37" fill="#548958"/><circle cx="512" cy="256" r="20" fill="#609b5e"/><path d="M209 333l5-13 6 12m206-4l5-13 5 11m-295 20l5-13 5 11" stroke="#6f9a55" stroke-width="3" fill="none"/><path d="M220 118q8-12 16 0q8-12 16 0m-6 30q7-10 14 0q7-10 14 0" stroke="#527965" stroke-width="3" fill="none" stroke-linecap="round"/><g transform="translate(88 346) rotate(-12)"><ellipse cy="29" rx="32" ry="8" fill="#649e94" opacity=".5"/><path d="M-25 0q25-17 50 0L17 24h-33Z" fill="#ffdc76" stroke="#d4a444" stroke-width="2"/><path d="M-18 2h36" stroke="#b68142" stroke-width="3"/><path d="M0-2v-39" stroke="#f7f2d3" stroke-width="4"/><path d="M4-39v34h25Z" fill="#fffaf0"/><path d="M-4-31v26h-22Z" fill="#e9ab70"/></g></svg>`;}
function home(){stopSpeech();state.screen='home';app.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">TAMAGAWA QUEST / 学校たんけんゲーム</div><h1>${r('きみの学校には、')}<br><span class="highlight">${r('ひみつがいっぱい。')}</span></h1><p>${r('芝生の校庭、まちのこと、なかまのこと。')}<br>${r('10問の冒険で、多摩川小学校をもっと知ろう！')}</p><button class="primary" id="start">${r('冒険に出発！')} <span aria-hidden="true">↗</span></button><p class="start-caption">${r('全50問からランダムに10問。時間制限はないよ。')}</p></div><div class="scene">${schoolScene()}<div class="mini-sticker"><span>あそぶたびに</span><b>10問</b><span>ちがう冒険！</span></div><div class="scene-label">HELLO, TAMAGAWA! 🌿</div></div></section><div class="features"><div class="feature"><span class="feature-icon">🎒</span><div><b>${r('1回10問の冒険')}</b><small>${r('あせらなくてOK')}</small></div></div><div class="feature"><span class="feature-icon">💡</span><div><b>${r('答えのあとに発見')}</b><small>${r('こたえにかいせつつき')}</small></div></div><div class="feature"><span class="feature-icon">🌱</span><div><b>${r('まちがえても成長')}</b><small>${r('なんどでもチャレンジ')}</small></div></div></div><div class="section-heading"><h2>${r('5つのひみつを探検しよう')}</h2><span>好きなテーマで練習もできるよ</span></div><div class="category-grid">${Object.entries(CATEGORIES).map(([id,c])=>`<button class="category-card" data-category="${id}" aria-label="${c.name}の10問を練習"><span class="icon" aria-hidden="true">${c.icon}</span><b>${r(c.name)}</b><small>${id==='life'?'生活クイズ':'学校クイズ'} · 10問で練習 ↗</small></button>`).join('')}</div><div class="bottom-strip"><p>🌟 ${r('発見した正解')} <b>${record.learned.length} / 50</b>　${r('最高記録')} <b>${record.best} / 10</b></p><button class="subtle" id="open-collection">${r('50問の発見図鑑を見る')} →</button></div>`;document.querySelector('#start').onclick=()=>startGame();app.querySelectorAll('[data-category]').forEach(btn=>btn.onclick=()=>startGame('category',btn.dataset.category));document.querySelector('#open-collection').onclick=()=>collection();syncSettings();}
function startGame(mode='normal',category,ids){stopSpeech();let pool=mode==='review'?QUESTIONS.filter(q=>ids.includes(q.id)):mode==='category'?QUESTIONS.filter(q=>q.category===category):QUESTIONS;const session=shuffle(pool).slice(0,10).map(q=>({...q,options:shuffle(q.choices)}));state={screen:'quiz',session,index:0,answers:[],mode,category,locked:false};scrollTop();renderQuestion();}
function renderQuestion(){stopSpeech();const q=state.session[state.index],c=CATEGORIES[q.category];const mode=state.mode==='normal'?'学校たんけん':state.mode==='review'?'もう一度チャレンジ':`${c.name}の練習`;app.innerHTML=`<section class="quest-shell"><div class="quest-header"><button class="subtle" id="leave">← ${r('ホームへ')}</button><span class="mode-label">${r(mode)}</span><span class="star-counter">★ ${state.answers.filter(a=>a.correct).length}</span></div><div class="quest-header"><div class="question-count">${state.index+1} <small>/ ${state.session.length} 問</small></div><small class="practice-note">${state.mode==='normal'?'毎回ランダムな10問':'テーマをしぼって練習中'}</small></div><div class="progress-map" aria-label="${state.index+1}問目、全${state.session.length}問">${state.session.map((_,i)=>`<span class="step ${i<state.index?'done':i===state.index?'current':''}"></span>`).join('')}</div><div class="quiz-card"><div class="card-meta"><span class="category-tag">${c.icon} ${r(c.name)}</span><button class="read-button" id="read" ${'speechSynthesis'in window?'':'disabled'} aria-label="問題と選択肢を読み上げる">◖)) ${r('読み上げ')}</button></div><h2 class="question-text">${r(q.text)}</h2><div class="choices" aria-label="答えを一つ選んでね">${q.options.map((option,i)=>`<button class="choice" data-option="${i}"><span class="choice-letter" aria-hidden="true">${['A','B','C'][i]}</span><span>${r(option)}</span><span class="answer-mark" aria-hidden="true"></span></button>`).join('')}</div><div id="answer-area" aria-live="polite" aria-atomic="true"></div></div><p class="quiz-hint">${r('答えだと思うものを1つ選んでね。まちがえても大丈夫！')}<br><span>キーボードでも遊べるよ：1・2・3 で答える</span></p></section>`;app.querySelectorAll('.choice').forEach(btn=>btn.onclick=()=>answerQuestion(Number(btn.dataset.option)));document.querySelector('#read').onclick=()=>readQuestion(q);document.querySelector('#leave').onclick=requestLeave;focusHeading();}
function readQuestion(q){stopSpeech();const convert=s=>s.replace(/河犬/g,'かけん').replace(/武蔵新田/g,'むさしにった');const speech=new SpeechSynthesisUtterance(convert(q.text)+'。'+q.options.map((o,i)=>`${i+1}番。${convert(o)}`).join('。'));speech.lang='ja-JP';speech.rate=.88;const voices=speechSynthesis.getVoices();const jp=voices.find(v=>v.lang.startsWith('ja'));if(jp)speech.voice=jp;speechSynthesis.speak(speech);}
function answerQuestion(index){if(state.screen!=='quiz'||state.locked||!Number.isInteger(index)||index<0||index>2)return;state.locked=true;stopSpeech();const q=state.session[state.index],selected=q.options[index],correct=selected===q.answer;state.answers.push({question:q,selected,correct});document.querySelector('.star-counter').textContent=`★ ${state.answers.filter(a=>a.correct).length}`;app.querySelectorAll('.choice').forEach((btn,i)=>{btn.disabled=true;if(q.options[i]===q.answer){btn.classList.add('correct');btn.querySelector('.answer-mark').textContent='○';btn.setAttribute('aria-label',`${q.options[i]}、正解`);}else if(i===index){btn.classList.add('wrong');btn.querySelector('.answer-mark').textContent='△';btn.setAttribute('aria-label',`${q.options[i]}、選んだ答え`);}else btn.classList.add('dim');});playSound(correct?'correct':'miss');const last=state.index===state.session.length-1;document.querySelector('#answer-area').innerHTML=`<div class="feedback ${correct?'':'missed'}"><h3>${correct?`🌟 ${r('正解！ ひみつを発見！')}`:`🌱 ${r('おしい！ ひとつ学べたね。')}`}</h3>${correct?'':`<p>${r('正解は')} <strong>「${r(q.answer)}」</strong></p>`}<p>${r(q.explanation)}</p><a class="source-link" href="${SOURCES[q.source].url}" target="_blank" rel="noopener noreferrer">${q.application?'目標をもとにしたオリジナル問題 · ':''}出典：${SOURCES[q.source].name} ↗</a></div><div class="next-row"><button id="next" class="primary">${r(last?'冒険の結果を見る':'次の問題へ')} <span aria-hidden="true">→</span></button></div>`;document.querySelector('#next').onclick=()=>{if(last)finishGame();else{state.index++;state.locked=false;renderQuestion();scrollTop();}};requestAnimationFrame(()=>document.querySelector('#next').focus({preventScroll:true}));}
function finishGame(){state.screen='result';stopSpeech();const score=state.answers.filter(a=>a.correct).length;if(state.mode==='normal'){record.plays++;record.best=Math.max(record.best,score);}record.learned=[...new Set([...record.learned,...state.answers.filter(a=>a.correct).map(a=>a.question.id)])];record.seen=[...new Set([...record.seen,...state.answers.map(a=>a.question.id)])];saveRecord();const misses=state.answers.filter(a=>!a.correct).map(a=>a.question.id);const title=score===10?'たまがわ博士、誕生！':score>=7?'学校たんけん名人！':score>=4?'ひみつハンター！':'冒険の第一歩、達成！';const message=score===10?'ぜんぶのひみつを見つけたね。次の冒険も待っているよ！':score>=7?'すてきな発見がたくさん！ もう一度で、もっとくわしくなれるよ。':'今日の発見は、きみの宝もの。もう一度やると、きっとわかるよ。';app.innerHTML=`<section class="quest-shell"><div class="result-heading"><div class="eyebrow">QUEST COMPLETE</div><div class="result-medal" aria-hidden="true">${score===10?'🏆':score>=7?'🏅':'🌻'}</div><h1>${r(title)}</h1><div class="score" aria-label="${state.session.length}問中${score}問正解">${score}<small> / ${state.session.length}問</small></div><p>${r(message)}</p>${state.mode==='normal'?'':`<p class="quiet-note">練習の結果だよ。最高記録はランダムな10問の冒険で更新できるよ。</p>`}</div><div class="result-buttons"><button class="primary" id="again">${r('新しい10問に挑戦')} ↗</button>${misses.length?`<button class="secondary" id="retry">${r('まちがえた問題を復習')} (${misses.length})</button>`:''}<button class="secondary" id="back-home">ホームへ</button></div><div class="result-card"><div class="result-summary"><div>${r('最高記録')}<b>${record.best} / 10</b></div><div>${r('図鑑の正解')}<b>${record.learned.length} / 50</b></div><div>${r('冒険した回数')}<b>${record.plays} 回</b></div></div><div class="section-heading"><h2>${r('今日の発見をふりかえろう')}</h2><span>タップで答えを見る</span></div>${state.answers.map(a=>reviewRow(a.question,a)).join('')}</div><p class="quiet-note">${r('まちがいは、新しい発見の入り口。何回でも遊んでね。')}</p></section>`;document.querySelector('#again').onclick=()=>startGame();document.querySelector('#back-home').onclick=()=>{home();scrollTop();focusHeading();};if(misses.length)document.querySelector('#retry').onclick=()=>startGame('review',null,misses);scrollTop();focusHeading();playSound('finish');celebrate();}
function reviewRow(q,result){return `<details class="review-row"><summary><span class="review-icon ${result&&!result.correct?'miss':''}" aria-hidden="true">${result?(result.correct?'○':'△'):CATEGORIES[q.category].icon}</span><span>${result?'':`<span class="collection-meta">No.${String(q.id).padStart(2,'0')} · ${CATEGORIES[q.category].name}${record.learned.includes(q.id)?'<span class="learned">✓ 正解したよ</span>':''}</span>`}${r(q.text)}</span><span class="review-arrow" aria-hidden="true">＋</span></summary><div class="review-body">${result&&!result.correct?`<p>きみの答え：${r(result.selected)}</p>`:''}<p>${r('正解')}：<strong>${r(q.answer)}</strong></p><p>${r(q.explanation)}</p><a class="source-link" href="${SOURCES[q.source].url}" target="_blank" rel="noopener noreferrer">${q.application?'生活クイズの参考：':'出典：'}${SOURCES[q.source].name} ↗</a></div></details>`;}
function collection(filter='all'){stopSpeech();state.screen='collection';const list=filter==='all'?QUESTIONS:QUESTIONS.filter(q=>q.category===filter);app.innerHTML=`<section class="quest-shell"><button class="subtle" id="back-home">← ホームへ</button><div class="collection-header"><div class="eyebrow">DISCOVERY NOTEBOOK</div><h1>${r('50問の発見図鑑')}</h1><p class="small">${r('答えを見て、学校のひみつを予習しよう。')}<br>${r('正解した問題')} ${record.learned.length} / 50 · ${r('出会った問題')} ${record.seen.length} / 50</p></div><div class="filter-tabs" aria-label="テーマで絞り込み"><button data-filter="all" class="${filter==='all'?'active':''}" aria-pressed="${filter==='all'}">すべて · 50</button>${Object.entries(CATEGORIES).map(([id,c])=>`<button data-filter="${id}" class="${filter===id?'active':''}" aria-pressed="${filter===id}">${c.icon} ${r(c.name)}</button>`).join('')}</div><div class="collection-list">${list.map(q=>reviewRow(q)).join('')}</div></section>`;app.querySelectorAll('[data-filter]').forEach(btn=>btn.onclick=()=>collection(btn.dataset.filter));document.querySelector('#back-home').onclick=()=>{home();scrollTop();focusHeading();};}
function celebrate(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const container=document.querySelector('#celebration');container.replaceChildren();for(let i=0;i<36;i++){const bit=document.createElement('i');bit.className='confetti';bit.style.left=`${Math.random()*100}%`;bit.style.background=['#ffda69','#4d9270','#69aeb4','#e5a77d'][i%4];bit.style.animationDelay=`${Math.random()*.65}s`;bit.style.transform=`rotate(${Math.random()*180}deg)`;container.append(bit);}setTimeout(()=>container.replaceChildren(),3400);}
function requestLeave(){stopSpeech();if(state.screen==='quiz')document.querySelector('#leave-dialog').showModal();else{home();scrollTop();focusHeading();}}
document.querySelector('#brand').onclick=event=>{event.preventDefault();requestLeave();};
document.querySelector('#ruby-toggle').onclick=()=>{record.ruby=!record.ruby;saveRecord();syncSettings();};
document.querySelector('#sound-toggle').onclick=()=>{record.sound=!record.sound;saveRecord();syncSettings();if(record.sound)playSound('correct');};
document.querySelector('#sources-button').onclick=()=>{stopSpeech();document.querySelector('#info-dialog').showModal();};
document.querySelector('#source-list').innerHTML=Object.values(SOURCES).map(s=>`<a href="${s.url}" target="_blank" rel="noopener noreferrer">${s.name} ↗</a>`).join('');
document.querySelector('.close-button').onclick=()=>document.querySelector('#info-dialog').close();
document.querySelector('#keep-playing').onclick=()=>document.querySelector('#leave-dialog').close();
document.querySelector('#confirm-leave').onclick=()=>{document.querySelector('#leave-dialog').close();home();scrollTop();focusHeading();};
document.querySelector('#clear-data').onclick=()=>{record={...DEFAULT_RECORD,learned:[],seen:[],ruby:record.ruby,sound:record.sound};saveRecord();syncSettings();document.querySelector('#clear-message').textContent='記録を消しました。';if(state.screen==='home')home();else if(state.screen==='collection')collection();};
document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const bounds=dialog.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)dialog.close();}}));
document.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]')||event.ctrlKey||event.altKey||event.metaKey||event.repeat)return;if(state.screen==='quiz'&&!state.locked&&['1','2','3'].includes(event.key)){event.preventDefault();answerQuestion(Number(event.key)-1);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopSpeech();});
window.addEventListener('pagehide',stopSpeech);
home();
